no reason to continue if source download fails

diff --git a/config/armv7l b/config/armv7l
--- a/config/armv7l
+++ b/config/armv7l
@@ -19,6 +19,9 @@ export OUTPUTDIR=$CWD/output
 if [ ! -f $CWD/toolchain/.arm-linux-gnueabihf ]; then
 if [ ! -f $CWD/dl/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz ]; then
     wget -P $CWD/dl/ https://releases.linaro.org/13.04/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading source: $1";exit 1
+    fi
 fi
 tar -vxf $CWD/dl/gcc-linaro-arm-linux-gnueabihf-4.7-2013.04-20130415_linux.tar.xz -C $CWD/toolchain --strip-components=1
 
