add some error handling for downloads

diff --git a/build/OpenSSL b/build/OpenSSL
--- a/build/OpenSSL
+++ b/build/OpenSSL
@@ -11,6 +11,9 @@ echo ">>>   MAKE zlib"
 sleep 3
 if [ ! -f $CWD/dl/zlib-1.2.8.tar.gz ]; then
     wget -O $CWD/dl/zlib-1.2.8.tar.gz http://zlib.net/zlib-1.2.8.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/zlib-1.2.8.tar.gz
 cd zlib-1.2.8/
@@ -26,6 +29,9 @@ echo ">>>   MAKE openssl"
 sleep 3
 if [ ! -f $CWD/dl/openssl-1.0.1e.tar.gz ]; then
     wget -O $CWD/dl/openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading openssl source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/openssl-1.0.1e.tar.gz
 cd openssl-1.0.1e/
@@ -41,6 +47,9 @@ echo ">>>   Get setuptools"
 sleep 3
 if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
     wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/setuptools-1.1.tar.gz 
 touch $CWD/code/.setuptools
@@ -61,6 +70,9 @@ echo ">>>   MAKE pyOpenSSL"
 sleep 3
 if [ ! -f $CWD/dl/pyOpenSSL-0.13.tar.gz ]; then
     wget -O $CWD/dl/pyOpenSSL-0.13.tar.gz http://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.13.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading pyOpenSSL source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/pyOpenSSL-0.13.tar.gz 
 cd pyOpenSSL-0.13/
diff --git a/build/lxml b/build/lxml
--- a/build/lxml
+++ b/build/lxml
@@ -11,6 +11,9 @@ echo ">>>   MAKE zlib"
 sleep 3
 if [ ! -f $CWD/dl/zlib-1.2.8.tar.gz ]; then
     wget -O $CWD/dl/zlib-1.2.8.tar.gz http://zlib.net/zlib-1.2.8.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/zlib-1.2.8.tar.gz
 cd zlib-1.2.8/
@@ -26,6 +29,9 @@ echo ">>>   MAKE libxml"
 sleep 3
 if [ ! -f $CWD/dl/libxml2-2.9.1.tar.gz ]; then
     wget -O $CWD/dl/libxml2-2.9.1.tar.gz ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading libxml2 source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/libxml2-2.9.1.tar.gz
 cd libxml2-2.9.1/
@@ -41,6 +47,9 @@ echo ">>>   MAKE libxslt"
 sleep 3
 if [ ! -f $CWD/dl/libxslt-1.1.28.tar.gz ]; then
     wget -O $CWD/dl/libxslt-1.1.28.tar.gz ftp://xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading libxslt source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/libxslt-1.1.28.tar.gz 
 cd libxslt-1.1.28/
@@ -56,6 +65,9 @@ echo ">>>   Get setuptools"
 sleep 3
 if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
     wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/setuptools-1.1.tar.gz 
 touch $CWD/code/.setuptools
@@ -76,6 +88,9 @@ echo ">>>   MAKE lxml"
 sleep 3
 if [ ! -f $CWD/dl/lxml-3.2.3.tar.gz ]; then
     wget -O $CWD/dl/lxml-3.2.3.tar.gz https://pypi.python.org/packages/source/l/lxml/lxml-3.2.3.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading lxml source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/lxml-3.2.3.tar.gz
 cd lxml-3.2.3/
diff --git a/build/python b/build/python
--- a/build/python
+++ b/build/python
@@ -12,6 +12,9 @@ echo ">>>   MAKE zlib"
 sleep 3
 if [ ! -f ../dl/zlib-1.2.8.tar.gz ]; then
     wget -O ../dl/zlib-1.2.8.tar.gz http://zlib.net/zlib-1.2.8.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/zlib-1.2.8.tar.gz
 cd zlib-1.2.8/
@@ -26,6 +29,9 @@ echo ">>>   MAKE bzip"
 sleep 3
 if [ ! -f ../dl/bzip2-1.0.6.tar.gz ]; then
     wget -P ../dl/ http://bzip.org/1.0.6/bzip2-1.0.6.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading bzip source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/bzip2-1.0.6.tar.gz
 cd bzip2-1.0.6/
@@ -42,6 +48,9 @@ echo ">>>   MAKE openssl"
 sleep 3
 if [ ! -f ../dl/openssl-1.0.1e.tar.gz ]; then
     wget -O ../dl/openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading openssl source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/openssl-1.0.1e.tar.gz
 cd openssl-1.0.1e/
@@ -56,6 +65,9 @@ echo ">>>   MAKE ncurses"
 sleep 3
 if [ ! -f ../dl/ncurses-5.9.tar.gz ]; then
     wget -O ../dl/ncurses-5.9.tar.gz http://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading ncurses source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/ncurses-5.9.tar.gz
 cd ncurses-5.9/
@@ -70,6 +82,9 @@ echo ">>>   MAKE sqlite"
 sleep 3
 if [ ! -f ../dl/sqlite-autoconf-3080000.tar.gz ]; then
     wget -O ../dl/sqlite-autoconf-3080000.tar.gz http://sqlite.org/2013/sqlite-autoconf-3080000.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading sqlite source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/sqlite-autoconf-3080000.tar.gz
 cd sqlite-autoconf-3080000/
@@ -84,6 +99,9 @@ echo ">>>   MAKE libffi"
 sleep 3
 if [ ! -f ../dl/libffi-3.0.13.tar.gz ]; then
     wget -O ../dl/libffi-3.0.13.tar.gz ftp://sourceware.org/pub/libffi/libffi-3.0.13.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading libffi source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/libffi-3.0.13.tar.gz
 cd libffi-3.0.13/
@@ -98,6 +116,9 @@ echo ">>>   MAKE Python"
 sleep 3
 if [ ! -f ../dl/Python-2.7.5.tgz ]; then
     wget -O ../dl/Python-2.7.5.tgz http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading Python source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf ../dl/Python-2.7.5.tgz
 cp -r Python-2.7.5 Python-2.7.5-native
diff --git a/build/unrar b/build/unrar
--- a/build/unrar
+++ b/build/unrar
@@ -9,6 +9,9 @@ echo ">>>   MAKE unrar"
 sleep 3
 if [ ! -f $CWD/dl/unrarsrc-5.0.12.tar.gz ]; then
     wget -O $CWD/dl/unrarsrc-5.0.12.tar.gz http://www.rarlab.com/rar/unrarsrc-5.0.12.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading unrar source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/unrarsrc-5.0.12.tar.gz
 cd unrar/
diff --git a/build/yEnc b/build/yEnc
--- a/build/yEnc
+++ b/build/yEnc
@@ -11,6 +11,9 @@ echo ">>>   Get setuptools"
 sleep 3
 if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
     wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/setuptools-1.1.tar.gz 
 touch $CWD/code/.setuptools
@@ -31,6 +34,9 @@ echo ">>>   MAKE yEnc"
 sleep 3
 if [ ! -f $CWD/dl/yenc-0.4.0.tar.gz ]; then
     wget -O $CWD/dl/yenc-0.4.0.tar.gz http://www.golug.it/pub/yenc/yenc-0.4.0.tar.gz
+    if [ "$?" -ne "0" ]; then
+      echo "error downloading yenc source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 fi
 tar zxf $CWD/dl/yenc-0.4.0.tar.gz
 cd yenc-0.4.0/
