no reason to make clean, package bumps, and fix lxml

diff --git a/build/OpenSSL b/build/OpenSSL
--- a/build/OpenSSL
+++ b/build/OpenSSL
@@ -17,33 +17,37 @@ if [ ! -f $CWD/code/.zlib-1.2.10 ]; then
     tar zxf $CWD/dl/zlib-1.2.10.tar.gz
     cd zlib-1.2.10/
     ./configure --prefix=$DEST --static
-    make clean && make
+    make
     if [ "$?" -ne "0" ]; then
         echo "error building zlib";. $CWD/config/cleanupenv.sh;exit 1
     fi
     ZLIB=`pwd`
     cd ..
     touch $CWD/code/.zlib-1.2.10
+else
+    ZLIB=`pwd`/zlib-1.2.10
 fi
 
-if [ ! -f $CWD/code/.openssl-1.0.2j ]; then
+if [ ! -f $CWD/code/.openssl-1.0.1e ]; then
     echo ">>>   MAKE openssl"
-    if [ ! -f $CWD/dl/openssl-1.0.2j.tar.gz ]; then
-        wget -O $CWD/dl/openssl-1.0.2j.tar.gz http://www.openssl.org/source/openssl-1.0.2j.tar.gz
+    if [ ! -f $CWD/dl/openssl-1.0.1e.tar.gz ]; then
+        wget -O $CWD/dl/openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
         if [ "$?" -ne "0" ]; then
             echo "error downloading openssl source";. $CWD/config/cleanupenv.sh;exit 1
         fi
     fi
-    tar zxf $CWD/dl/openssl-1.0.2j.tar.gz
-    cd openssl-1.0.2j/
+    tar zxf $CWD/dl/openssl-1.0.1e.tar.gz
+    cd openssl-1.0.1e/
     ./Configure --prefix=$DEST --openssldir=$DEST/etc/ssl --with-zlib-include=$ZLIB --with-zlib-lib=$ZLIB no-zlib-dynamic threads linux-armv4 -DL_ENDIAN $CFLAGS $LDFLAGS
-    make -j1 clean && make -j1
+    make -j1
     if [ "$?" -ne "0" ]; then
         echo "error building openssl";. $CWD/config/cleanupenv.sh;exit 1
     fi
     OPENSSL=`pwd`
     cd ..
-    touch $CWD/code/.openssl-1.0.2j
+    touch $CWD/code/.openssl-1.0.1e
+else
+    OPENSSL=`pwd`/openssl-1.0.1e
 fi
 
 if [ ! -f $CWD/code/.setuptools ]; then
@@ -62,7 +66,7 @@ if [ ! -f $CWD/code/.lib.linux2-arm-2.7 ]; then
     echo ">>>   Link to Python Build environment"
     cd $CWD/code/Python-2.7.5/build
     mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
-    ln -s ../../Python-2.7.5-native/build/lib.linux-$HOST_ARCH-2.7 lib.linux2-arm-2.7
+    ln -s ../../Python-2.7.5-native/build/lib.linux-${HOST_ARCH}-2.7 lib.linux2-arm-2.7
     cd $CWD/code
     touch $CWD/code/.lib.linux2-arm-2.7
 fi
@@ -81,8 +85,17 @@ if [ ! -f $CWD/code/.OpenSSL ]; then
     export _PYTHON_HOST_PLATFORM="linux-armv7l"
     sed -i -e "s|from distutils.core import Extension, setup|from setuptools import setup\nfrom distutils.core import Extension|g" setup.py
     PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py build_ext -I$OPENSSL/include -L$OPENSSL
+    if [ "$?" -ne "0" ]; then
+        echo "error building openssl";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     $STRIP build/lib.linux-armv7l-2.7/OpenSSL/*.so
+    if [ "$?" -ne "0" ]; then
+        echo "error building openssl";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py bdist_egg
+    if [ "$?" -ne "0" ]; then
+        echo "error building openssl";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     cd ..
     touch $CWD/code/.OpenSSL
 fi
diff --git a/build/cheetah b/build/cheetah
--- a/build/cheetah
+++ b/build/cheetah
@@ -11,7 +11,7 @@ if [ ! -f $CWD/code/.setuptools ]; then
     if [ ! -f $CWD/dl/setuptools-32.3.1.zip ]; then
         wget -O $CWD/dl/setuptools-32.3.1.zip https://pypi.python.org/packages/e8/68/f968ebc015c7e0021e76b60b8cfd29f9ffbae4b3b58d96ad20045a99562e/setuptools-32.3.1.zip
         if [ "$?" -ne "0" ]; then
-                echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+            echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
         fi
     fi
     unzip $CWD/dl/setuptools-32.3.1.zip
@@ -40,6 +40,9 @@ if [ ! -f $CWD/code/.Cheetah ]; then
     export LDSHARED="$CC -pthread -shared"
     export _PYTHON_HOST_PLATFORM="linux-armv7l"
     PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython ./setup.py bdist_egg
+    if [ "$?" -ne "0" ]; then
+        echo "error building Cheetah";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     touch $CWD/code/.Cheetah
 fi
 
diff --git a/build/lxml b/build/lxml
--- a/build/lxml
+++ b/build/lxml
@@ -20,13 +20,15 @@ if [ ! -f $CWD/code/.zlib-1.2.10 ]; then
     fi
     cd zlib-1.2.10/
     ./configure --prefix=$DEST --static
-    make clean && make
+    make
     if [ "$?" -ne "0" ]; then
         echo "error building zlib";. $CWD/config/cleanupenv.sh;exit 1
     fi
     ZLIB=`pwd`
     cd ..
     touch $CWD/code/.zlib-1.2.10
+else
+    ZLIB=`pwd`/zlib-1.2.10
 fi
 
 if [ ! -f $CWD/code/.libxml2-2.9.4 ]; then
@@ -39,14 +41,16 @@ if [ ! -f $CWD/code/.libxml2-2.9.4 ]; then
     fi
     tar zxf $CWD/dl/libxml2-2.9.4.tar.gz
     cd libxml2-2.9.4/
-    ./configure --host=$CHOST --prefix=$DEST --with-zlib --without-python --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
-    make clean && make
+    ./configure --host=$CHOST --prefix=$DEST --with-zlib --without-python --enable-static --enable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
+    make && make install
     if [ "$?" -ne "0" ]; then
         echo "error building libxml2";. $CWD/config/cleanupenv.sh;exit 1
     fi
     LIBXML=`pwd`
     cd ..
     touch $CWD/code/.libxml2-2.9.4
+else
+    LIBXML=`pwd`/libxml2-2.9.4
 fi
 
 if [ ! -f $CWD/code/.libxslt-1.1.29 ]; then
@@ -59,11 +63,16 @@ if [ ! -f $CWD/code/.libxslt-1.1.29 ]; then
     fi
     tar zxf $CWD/dl/libxslt-1.1.29.tar.gz 
     cd libxslt-1.1.29/
-    ./configure --host=$CHOST --prefix=$DEST --without-python --with-libxml-src=$LIBXML --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
-    make clean && make
+    ./configure --host=$CHOST --prefix=$DEST --without-python --without-crypto --with-libxml-prefix=$DEST --enable-static --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
+    make && make install
+    if [ "$?" -ne "0" ]; then
+        echo "error building libxslt";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     LIBXSLT=`pwd`
     cd ..
     touch $CWD/code/.libxslt-1.1.29
+else
+    LIBXSLT=`pwd`/libxslt-1.1.29
 fi
 
 if [ ! -f $CWD/code/.setuptools ]; then
@@ -82,7 +91,7 @@ if [ ! -f $CWD/code/.lib.linux2-arm-2.7 ]; then
     echo ">>>   Link to Python Build environment"
     cd $CWD/code/Python-2.7.5/build
     mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
-    ln -s ../../Python-2.7.5-native/build/lib.linux-$HOST_ARCH-2.7 lib.linux2-arm-2.7
+    ln -s ../../Python-2.7.5-native/build/lib.linux-${HOST_ARCH}-2.7 lib.linux2-arm-2.7
     cd $CWD/code
     touch $CWD/code/.lib.linux2-arm-2.7
 fi
@@ -99,9 +108,10 @@ if [ ! -f $CWD/code/.lxml ]; then
     cd lxml-3.7.2/
     export LDSHARED="$CC -pthread -shared"
     export _PYTHON_HOST_PLATFORM="linux-armv7l"
-    PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py build_ext -I$LIBXML/include:$LIBXSLT:$ZLIB -L$LIBXML/.libs:$LIBXSLT/libxslt/.libs:$LIBXSLT/libexslt/.libs:$ZLIB -lrt
-    $STRIP build/lib.linux-armv7l-2.7/lxml/*.so
-    PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py bdist_egg
+    PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py build_ext --with-xslt-config=$DEST/bin/xslt-config -I$LIBXML/include:$LIBXSLT:$ZLIB -L$LIBXML/.libs:$LIBXSLT/libxslt/.libs:$LIBXSLT/libexslt/.libs:$ZLIB -lrt && $STRIP build/lib.linux-armv7l-2.7/lxml/*.so
+    if [ "$?" -ne "0" ]; then
+        echo "error building lxml";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     cd ..
     touch $CWD/code/.lxml
 fi
diff --git a/build/yEnc b/build/yEnc
--- a/build/yEnc
+++ b/build/yEnc
@@ -41,6 +41,9 @@ if [ ! -f $CWD/code/.yEnc ]; then
     export _PYTHON_HOST_PLATFORM="linux-armv7l"
     sed -i -e "s|from distutils.core import setup, Extension|from setuptools import setup\nfrom distutils.core import Extension|g" setup.py
     PYTHONPATH=../setuptools-32.3.1 ../Python-2.7.5/hostpython setup.py bdist_egg
+    if [ "$?" -ne "0" ]; then
+        echo "error building yenc";. $CWD/config/cleanupenv.sh;exit 1
+    fi
     cd ../
     touch $CWD/code/.yEnc
 fi
