remove sleeps, styling, and moved python patch to its own file

diff --git a/build/OpenSSL b/build/OpenSSL
--- a/build/OpenSSL
+++ b/build/OpenSSL
@@ -7,92 +7,86 @@ export CFLAGS="$CFLAGS -Os -fPIC -ffunction-sections -fdata-sections"
 export LDFLAGS="$LDFLAGS -Wl,--gc-sections"
 
 if [ ! -f $CWD/code/.zlib-1.2.10 ]; then
-echo ">>>   MAKE zlib"
-sleep 3
-if [ ! -f $CWD/dl/zlib-1.2.10.tar.gz ]; then
-    wget -O $CWD/dl/zlib-1.2.10.tar.gz http://zlib.net/zlib-1.2.10.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE zlib"
+    if [ ! -f $CWD/dl/zlib-1.2.10.tar.gz ]; then
+        wget -O $CWD/dl/zlib-1.2.10.tar.gz http://zlib.net/zlib-1.2.10.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/zlib-1.2.10.tar.gz
-cd zlib-1.2.10/
-./configure --prefix=$DEST --static
-make clean && make
-ZLIB=`pwd`
-cd ..
-touch $CWD/code/.zlib-1.2.10
+    tar zxf $CWD/dl/zlib-1.2.10.tar.gz
+    cd zlib-1.2.10/
+    ./configure --prefix=$DEST --static
+    make clean && make
+    ZLIB=`pwd`
+    cd ..
+    touch $CWD/code/.zlib-1.2.10
 fi
 
 if [ ! -f $CWD/code/.openssl-1.0.1e ]; then
-echo ">>>   MAKE openssl"
-sleep 3
-if [ ! -f $CWD/dl/openssl-1.0.1e.tar.gz ]; then
-    wget -O $CWD/dl/openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading openssl source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE openssl"
+    if [ ! -f $CWD/dl/openssl-1.0.1e.tar.gz ]; then
+        wget -O $CWD/dl/openssl-1.0.1e.tar.gz http://www.openssl.org/source/openssl-1.0.1e.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading openssl source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/openssl-1.0.1e.tar.gz
-cd openssl-1.0.1e/
-./Configure --prefix=$DEST --openssldir=$DEST/etc/ssl --with-zlib-include=$ZLIB --with-zlib-lib=$ZLIB no-shared no-zlib-dynamic threads linux-armv4 -DL_ENDIAN $CFLAGS $LDFLAGS
-make -j1 clean && make -j1
-OPENSSL=`pwd`
-cd ..
-touch $CWD/code/.openssl-1.0.1e
+    tar zxf $CWD/dl/openssl-1.0.1e.tar.gz
+    cd openssl-1.0.1e/
+    ./Configure --prefix=$DEST --openssldir=$DEST/etc/ssl --with-zlib-include=$ZLIB --with-zlib-lib=$ZLIB no-shared no-zlib-dynamic threads linux-armv4 -DL_ENDIAN $CFLAGS $LDFLAGS
+    make -j1 clean && make -j1
+    OPENSSL=`pwd`
+    cd ..
+    touch $CWD/code/.openssl-1.0.1e
 fi
 
 if [ ! -f $CWD/code/.setuptools ]; then
-echo ">>>   Get setuptools"
-sleep 3
-if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
-    wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   Get setuptools"
+    if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
+        wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/setuptools-1.1.tar.gz 
-touch $CWD/code/.setuptools
+    tar zxf $CWD/dl/setuptools-1.1.tar.gz 
+    touch $CWD/code/.setuptools
 fi
 
 if [ ! -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Link to Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
-ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
-popd
-touch $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Link to Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
+    ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
+    popd
+    touch $CWD/code/.lib.linux2-arm-2.7
 fi
 
 if [ ! -f $CWD/code/.OpenSSL ]; then
-echo ">>>   MAKE pyOpenSSL"
-sleep 3
-if [ ! -f $CWD/dl/pyOpenSSL-0.13.tar.gz ]; then
-    wget -O $CWD/dl/pyOpenSSL-0.13.tar.gz http://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.13.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading pyOpenSSL source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE pyOpenSSL"
+    if [ ! -f $CWD/dl/pyOpenSSL-0.13.tar.gz ]; then
+        wget -O $CWD/dl/pyOpenSSL-0.13.tar.gz http://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.13.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading pyOpenSSL source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/pyOpenSSL-0.13.tar.gz 
-cd pyOpenSSL-0.13/
-export LDSHARED="$CC -pthread -shared"
-export _PYTHON_HOST_PLATFORM="linux-armv7l"
-sed -i -e "s|from distutils.core import Extension, setup|from setuptools import setup\nfrom distutils.core import Extension|g" setup.py
-PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py build_ext -I$OPENSSL/include -L$OPENSSL
-$STRIP build/lib.linux-armv7l-2.7/OpenSSL/*.so
-PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py bdist_egg
-touch $CWD/code/.OpenSSL
+    tar zxf $CWD/dl/pyOpenSSL-0.13.tar.gz 
+    cd pyOpenSSL-0.13/
+    export LDSHARED="$CC -pthread -shared"
+    export _PYTHON_HOST_PLATFORM="linux-armv7l"
+    sed -i -e "s|from distutils.core import Extension, setup|from setuptools import setup\nfrom distutils.core import Extension|g" setup.py
+    PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py build_ext -I$OPENSSL/include -L$OPENSSL
+    $STRIP build/lib.linux-armv7l-2.7/OpenSSL/*.so
+    PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py bdist_egg
+    touch $CWD/code/.OpenSSL
 fi
 
 if [ -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Unlink Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-rm lib.linux2-arm-2.7
-mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
-popd
-rm $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Unlink Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    rm lib.linux2-arm-2.7
+    mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
+    popd
+    rm $CWD/code/.lib.linux2-arm-2.7
 fi
 
 cd $CWD
@@ -100,4 +94,3 @@ echo
 echo "##################################"
 echo "+++   OpenSSL build complete   +++"
 echo "##################################"
-sleep 3
diff --git a/build/cheetah b/build/cheetah
--- a/build/cheetah
+++ b/build/cheetah
@@ -7,53 +7,49 @@ export CFLAGS="$CFLAGS -Os -fPIC -ffunction-sections -fdata-sections"
 export LDFLAGS="$LDFLAGS -Wl,--gc-sections"
 
 if [ ! -f $CWD/code/.setuptools ]; then
-echo ">>>   Get setuptools"
-sleep 3
-if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
-    wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   Get setuptools"
+    if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
+        wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+        if [ "$?" -ne "0" ]; then
+                echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/setuptools-1.1.tar.gz 
-touch $CWD/code/.setuptools
+    tar zxf $CWD/dl/setuptools-1.1.tar.gz 
+    touch $CWD/code/.setuptools
 fi
 
 if [ ! -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Link to Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
-ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
-popd
-touch $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Link to Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
+    ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
+    popd
+    touch $CWD/code/.lib.linux2-arm-2.7
 fi
 
 if [ ! -f $CWD/code/.Cheetah ]; then
-echo ">>>   MAKE Cheetah"
-sleep 3
-if [ ! -f $CWD/dl/Cheetah-2.4.4.tar.gz ]; then
-    wget -O $CWD/dl/Cheetah-2.4.4.tar.gz http://pypi.python.org/packages/source/C/Cheetah/Cheetah-2.4.4.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading cheetah source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE Cheetah"
+    if [ ! -f $CWD/dl/Cheetah-2.4.4.tar.gz ]; then
+        wget -O $CWD/dl/Cheetah-2.4.4.tar.gz http://pypi.python.org/packages/source/C/Cheetah/Cheetah-2.4.4.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading cheetah source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/Cheetah-2.4.4.tar.gz
-cd Cheetah-2.4.4/
-export LDSHARED="$CC -pthread -shared"
-export _PYTHON_HOST_PLATFORM="linux-armv7l"
-PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython ./setup.py bdist_egg
-touch $CWD/code/.Cheetah
+    tar zxf $CWD/dl/Cheetah-2.4.4.tar.gz
+    cd Cheetah-2.4.4/
+    export LDSHARED="$CC -pthread -shared"
+    export _PYTHON_HOST_PLATFORM="linux-armv7l"
+    PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython ./setup.py bdist_egg
+    touch $CWD/code/.Cheetah
 fi
 
 if [ -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Unlink Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-rm lib.linux2-arm-2.7
-mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
-popd
-rm $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Unlink Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    rm lib.linux2-arm-2.7
+    mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
+    popd
+    rm $CWD/code/.lib.linux2-arm-2.7
 fi
 
 cd $CWD
@@ -61,4 +57,3 @@ echo
 echo "##################################"
 echo "+++   Cheetah build complete   +++"
 echo "##################################"
-sleep 3
diff --git a/build/lxml b/build/lxml
--- a/build/lxml
+++ b/build/lxml
@@ -7,109 +7,105 @@ export CFLAGS="$CFLAGS -Os -fPIC -ffunction-sections -fdata-sections"
 export LDFLAGS="$LDFLAGS -Wl,--gc-sections"
 
 if [ ! -f $CWD/code/.zlib-1.2.10 ]; then
-echo ">>>   MAKE zlib"
-sleep 3
-if [ ! -f $CWD/dl/zlib-1.2.10.tar.gz ]; then
-    wget -O $CWD/dl/zlib-1.2.10.tar.gz http://zlib.net/zlib-1.2.10.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE zlib"
+    if [ ! -f $CWD/dl/zlib-1.2.10.tar.gz ]; then
+        wget -O $CWD/dl/zlib-1.2.10.tar.gz http://zlib.net/zlib-1.2.10.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading zlib source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/zlib-1.2.10.tar.gz
-cd zlib-1.2.10/
-./configure --prefix=$DEST --static
-make clean && make
-ZLIB=`pwd`
-cd ..
-touch $CWD/code/.zlib-1.2.10
+    tar zxf $CWD/dl/zlib-1.2.10.tar.gz
+    if [ "$?" -ne "0" ]; then
+        echo "error unpacking zlib source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
+    cd zlib-1.2.10/
+    ./configure --prefix=$DEST --static
+    make clean && make
+    ZLIB=`pwd`
+    cd ..
+    touch $CWD/code/.zlib-1.2.10
 fi
 
 if [ ! -f $CWD/code/.libxml2-2.9.1 ]; then
-echo ">>>   MAKE libxml"
-sleep 3
-if [ ! -f $CWD/dl/libxml2-2.9.1.tar.gz ]; then
-    wget -O $CWD/dl/libxml2-2.9.1.tar.gz ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading libxml2 source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE libxml"
+    if [ ! -f $CWD/dl/libxml2-2.9.1.tar.gz ]; then
+        wget -O $CWD/dl/libxml2-2.9.1.tar.gz ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading libxml2 source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/libxml2-2.9.1.tar.gz
-cd libxml2-2.9.1/
-./configure --host=$CHOST --prefix=$DEST --with-zlib --without-python --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
-make clean && make
-LIBXML=`pwd`
-cd ..
-touch $CWD/code/.libxml2-2.9.1
+    tar zxf $CWD/dl/libxml2-2.9.1.tar.gz
+    cd libxml2-2.9.1/
+    ./configure --host=$CHOST --prefix=$DEST --with-zlib --without-python --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
+    make clean && make
+    LIBXML=`pwd`
+    cd ..
+    touch $CWD/code/.libxml2-2.9.1
 fi
 
 if [ ! -f $CWD/code/.libxslt-1.1.28 ]; then
-echo ">>>   MAKE libxslt"
-sleep 3
-if [ ! -f $CWD/dl/libxslt-1.1.28.tar.gz ]; then
-    wget -O $CWD/dl/libxslt-1.1.28.tar.gz ftp://xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading libxslt source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE libxslt"
+    if [ ! -f $CWD/dl/libxslt-1.1.28.tar.gz ]; then
+        wget -O $CWD/dl/libxslt-1.1.28.tar.gz ftp://xmlsoft.org/libxml2/libxslt-1.1.28.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading libxslt source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/libxslt-1.1.28.tar.gz 
-cd libxslt-1.1.28/
-./configure --host=$CHOST --prefix=$DEST --without-python --with-libxml-src=$LIBXML --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
-make clean && make
-LIBXSLT=`pwd`
-cd ..
-touch $CWD/code/.libxslt-1.1.28
+    tar zxf $CWD/dl/libxslt-1.1.28.tar.gz 
+    cd libxslt-1.1.28/
+    ./configure --host=$CHOST --prefix=$DEST --without-python --with-libxml-src=$LIBXML --disable-shared CPPFLAGS="-I$ZLIB" LDFLAGS="$LDFLAGS -L$ZLIB"
+    make clean && make
+    LIBXSLT=`pwd`
+    cd ..
+    touch $CWD/code/.libxslt-1.1.28
 fi
 
 if [ ! -f $CWD/code/.setuptools ]; then
-echo ">>>   Get setuptools"
-sleep 3
-if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
-    wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   Get setuptools"
+    if [ ! -f $CWD/dl/setuptools-1.1.tar.gz ]; then
+        wget -O $CWD/dl/setuptools-1.1.tar.gz https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading setuptools source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/setuptools-1.1.tar.gz 
-touch $CWD/code/.setuptools
+    tar zxf $CWD/dl/setuptools-1.1.tar.gz 
+    touch $CWD/code/.setuptools
 fi
 
 if [ ! -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Link to Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
-ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
-popd
-touch $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Link to Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    mv lib.linux2-arm-2.7 lib.linux2-arm-2.7.orig
+    ln -s ../../Python-2.7.5-native/build/lib.linux-i686-2.7 lib.linux2-arm-2.7
+    popd
+    touch $CWD/code/.lib.linux2-arm-2.7
 fi
 
 if [ ! -f $CWD/code/.lxml ]; then
-echo ">>>   MAKE lxml"
-sleep 3
-if [ ! -f $CWD/dl/lxml-3.2.3.tar.gz ]; then
-    wget -O $CWD/dl/lxml-3.2.3.tar.gz https://pypi.python.org/packages/source/l/lxml/lxml-3.2.3.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading lxml source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE lxml"
+    if [ ! -f $CWD/dl/lxml-3.2.3.tar.gz ]; then
+        wget -O $CWD/dl/lxml-3.2.3.tar.gz https://pypi.python.org/packages/source/l/lxml/lxml-3.2.3.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading lxml source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/lxml-3.2.3.tar.gz
-cd lxml-3.2.3/
-export LDSHARED="$CC -pthread -shared"
-export _PYTHON_HOST_PLATFORM="linux-armv7l"
-PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py build_ext -I$LIBXML/include:$LIBXSLT:$ZLIB -L$LIBXML/.libs:$LIBXSLT/libxslt/.libs:$LIBXSLT/libexslt/.libs:$ZLIB -lrt
-$STRIP build/lib.linux-armv7l-2.7/lxml/*.so
-PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py bdist_egg
-touch $CWD/code/.lxml
+    tar zxf $CWD/dl/lxml-3.2.3.tar.gz
+    cd lxml-3.2.3/
+    export LDSHARED="$CC -pthread -shared"
+    export _PYTHON_HOST_PLATFORM="linux-armv7l"
+    PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py build_ext -I$LIBXML/include:$LIBXSLT:$ZLIB -L$LIBXML/.libs:$LIBXSLT/libxslt/.libs:$LIBXSLT/libexslt/.libs:$ZLIB -lrt
+    $STRIP build/lib.linux-armv7l-2.7/lxml/*.so
+    PYTHONPATH=../setuptools-1.1 ../Python-2.7.5/hostpython setup.py bdist_egg
+    touch $CWD/code/.lxml
 fi
 
 if [ -f $CWD/code/.lib.linux2-arm-2.7 ]; then
-echo ">>>   Unlink Python Build environment"
-sleep 3
-pushd $CWD/code/Python-2.7.5/build
-rm lib.linux2-arm-2.7
-mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
-popd
-rm $CWD/code/.lib.linux2-arm-2.7
+    echo ">>>   Unlink Python Build environment"
+    pushd $CWD/code/Python-2.7.5/build
+    rm lib.linux2-arm-2.7
+    mv lib.linux2-arm-2.7.orig lib.linux2-arm-2.7
+    popd
+    rm $CWD/code/.lib.linux2-arm-2.7
 fi
 
 cd $CWD
@@ -117,4 +113,3 @@ echo
 echo "###############################"
 echo "+++   lxml build complete   +++"
 echo "###############################"
-sleep 3
diff --git a/build/overlay b/build/overlay
--- a/build/overlay
+++ b/build/overlay
@@ -7,17 +7,16 @@ mkdir -p $CWD/code/overlay/lib
 touch $CWD/code/overlay/lib/__init__.py
 
 if [ ! -f $CWD/code/.configobj ]; then
-echo ">>>   Get ConfigObj"
-sleep 3
-if [ ! -f $CWD/dl/configobj-4.7.2.zip ]; then
-    wget -O $CWD/dl/configobj-4.7.2.zip www.voidspace.org.uk/downloads/configobj-4.7.2.zip
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading configobj source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   Get ConfigObj"
+    if [ ! -f $CWD/dl/configobj-4.7.2.zip ]; then
+        wget -O $CWD/dl/configobj-4.7.2.zip www.voidspace.org.uk/downloads/configobj-4.7.2.zip
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading configobj source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-unzip -o $CWD/dl/configobj-4.7.2.zip -d $CWD/code/configobj
-cp -avr $CWD/code/configobj/configobj-4.7.2/configobj.py $CWD/code/overlay/lib/
-touch $CWD/code/.configobj
+    unzip -o $CWD/dl/configobj-4.7.2.zip -d $CWD/code/configobj
+    cp -avr $CWD/code/configobj/configobj-4.7.2/configobj.py $CWD/code/overlay/lib/
+    touch $CWD/code/.configobj
 fi
 
 
diff --git a/build/par2 b/build/par2
--- a/build/par2
+++ b/build/par2
@@ -5,27 +5,26 @@ cd $CWD/code
 export DEST=$OUTPUTDIR/par2
 
 if [ ! -f $CWD/code/.par2cmdline ]; then
-echo ">>>   MAKE par2"
-sleep 3
-if [ ! -f $CWD/dl/par2cmdline-0.4.tar.gz ]; then
-    wget -O $CWD/dl/par2cmdline-0.4.tar.gz http://sourceforge.net/projects/parchive/files/par2cmdline/0.4/par2cmdline-0.4.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading par2cmdline source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE par2"
+    if [ ! -f $CWD/dl/par2cmdline-0.4.tar.gz ]; then
+        wget -O $CWD/dl/par2cmdline-0.4.tar.gz http://sourceforge.net/projects/parchive/files/par2cmdline/0.4/par2cmdline-0.4.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading par2cmdline source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/par2cmdline-0.4.tar.gz 
-cd par2cmdline-0.4/
-echo ">>>   Patching par2"
-wget --no-check-certificate -O reedsolomon.cpp.patch https://102391.bugs.gentoo.org/attachment.cgi?id=65851
-if [ "$?" -ne "0" ]; then
-  echo "error downloading patch";. $CWD/config/cleanupenv.sh;exit 1
-fi
-patch reedsolomon.cpp reedsolomon.cpp.patch
-if [ "$?" -ne "0" ]; then
-  echo "error patching source";. $CWD/config/cleanupenv.sh;exit 1
-fi
-CFLAGS="$CFLAGS -O3" ./configure --host=$CHOST --prefix=$DEST
-make clean && make && make install
-$STRIP $DEST/bin/*
-touch $CWD/code/.par2cmdline
+    tar zxf $CWD/dl/par2cmdline-0.4.tar.gz 
+    cd par2cmdline-0.4/
+    echo ">>>   Patching par2"
+    wget --no-check-certificate -O reedsolomon.cpp.patch https://102391.bugs.gentoo.org/attachment.cgi?id=65851
+    if [ "$?" -ne "0" ]; then
+        echo "error downloading patch";. $CWD/config/cleanupenv.sh;exit 1
+    fi
+    patch reedsolomon.cpp reedsolomon.cpp.patch
+    if [ "$?" -ne "0" ]; then
+        echo "error patching source";. $CWD/config/cleanupenv.sh;exit 1
+    fi
+    CFLAGS="$CFLAGS -O3" ./configure --host=$CHOST --prefix=$DEST
+    make clean && make && make install
+    $STRIP $DEST/bin/*
+    touch $CWD/code/.par2cmdline
 fi
diff --git a/build/unrar b/build/unrar
--- a/build/unrar
+++ b/build/unrar
@@ -5,19 +5,18 @@ cd $CWD/code
 export DEST=$OUTPUTDIR/unrar
 
 if [ ! -f $CWD/code/.unrar ]; then
-echo ">>>   MAKE unrar"
-sleep 3
-if [ ! -f $CWD/dl/unrarsrc-5.0.12.tar.gz ]; then
-    wget -O $CWD/dl/unrarsrc-5.0.12.tar.gz http://www.rarlab.com/rar/unrarsrc-5.0.12.tar.gz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading unrar source";. $CWD/config/cleanupenv.sh;exit 1
+    echo ">>>   MAKE unrar"
+    if [ ! -f $CWD/dl/unrarsrc-5.0.12.tar.gz ]; then
+        wget -O $CWD/dl/unrarsrc-5.0.12.tar.gz http://www.rarlab.com/rar/unrarsrc-5.0.12.tar.gz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading unrar source";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar zxf $CWD/dl/unrarsrc-5.0.12.tar.gz
-cd unrar/
-mv makefile Makefile
-make clean
-make CXX=$CXX CXXFLAGS="$CFLAGS -Os -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE" STRIP=$STRIP LDFLAGS="-pthread"
-make install DESTDIR=$DEST
-touch $CWD/code/.unrar
+    tar zxf $CWD/dl/unrarsrc-5.0.12.tar.gz
+    cd unrar/
+    mv makefile Makefile
+    make clean
+    make CXX=$CXX CXXFLAGS="$CFLAGS -Os -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE" STRIP=$STRIP LDFLAGS="-pthread"
+    make install DESTDIR=$DEST
+    touch $CWD/code/.unrar
 fi
diff --git a/config/armv7l b/config/armv7l
--- a/config/armv7l
+++ b/config/armv7l
@@ -17,15 +17,18 @@ export OUTPUTDIR=$CWD/output
 
 ### Download and install toolchain
 if [ ! -f $CWD/toolchain/.arm-linux-gnueabihf ]; then
-if [ ! -f $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz ]; then
-    wget -P $CWD/dl/ https://releases.linaro.org/components/toolchain/binaries/latest/armeb-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz
-    if [ "$?" -ne "0" ]; then
-      echo "error downloading source: $1";. $CWD/config/cleanupenv.sh;exit 1
+    if [ ! -f $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz ]; then
+        wget -P $CWD/dl/ https://releases.linaro.org/components/toolchain/binaries/latest/armeb-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz
+        if [ "$?" -ne "0" ]; then
+            echo "error downloading source: $1";. $CWD/config/cleanupenv.sh;exit 1
+        fi
     fi
-fi
-tar -vxf $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz -C $CWD/toolchain --strip-components=1
+    tar -vxf $CWD/dl/gcc-linaro-6.2.1-2016.11-x86_64_armeb-linux-gnueabihf.tar.xz -C $CWD/toolchain --strip-components=1
+    if [ "$?" -ne "0" ]; then
+        echo "error unpacking source: $1";. $CWD/config/cleanupenv.sh;exit 1
+    fi
 
-touch $CWD/toolchain/.arm-linux-gnueabihf
+    touch $CWD/toolchain/.arm-linux-gnueabihf
 fi
 
 echo
